util: when bootstrapped, return self path as wrapper
Avoid reporting itself via the true path of the script; use
the wrapper instead. That is, instead of

```
Error: Argument missing. See '$HOME/.luarocks/lib/luarocks/rocks-5.3/luarocks/dev-1/bin/luarocks help install'.
```

report

```
Error: Argument missing. See '$HOME/.luarocks/bin/luarocks help install'.
```

See https://github.com/luarocks/luarocks/issues/952#issuecomment-449966779